import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import QueryContextProvider from "@/components/shared/QueryContextProvider";
import { ThemeProvider } from "@/components/shared/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
			  <QueryContextProvider>
          <body className={inter.className}>
            <ThemeProvider attribute="class">
              {children}
            </ThemeProvider>
          </body>
			  </QueryContextProvider>
    </html>
  );
}
